### ISSUE TITLE
viewport reference

### ISSUE THREAD

**Issue by lamstutz** [Moventes/bruit.io#12]
si on place le composant dans un element avec une propriété transform, perspective ou filter qui est différente de none... la modal ce place par rapport a cet attribut.

https://developer.mozilla.org/fr/docs/Web/CSS/position

solution :
- placer le composant a la racine (body) et faire un bouton qui declenche un evenement qui ouvre la modal ?
- la modal fait un appendChild sur body ?

**Comment by ghost** [comment]
WIP sur branch split-component

pour faire une pré release : 
npm publish --tag next (=> npm install xxx@nex, crée une release au format x.y.z-w)

Manque la gestion des erreurs

To be tested

=> changer la doc, l'install a changée (ajouter trois lignes en web, cf photo pour Angular)
