### ISSUE TITLE
Impossible de typer les données sur le composant

### ISSUE THREAD

**Issue by ghost** [Moventes/bruit.io#20]
Constaté sur PITANGOO web

J'ai créé un attribut bruitData que je passe en paramètre au composant bruit.io

footer.component.ts
```
public readonly bruitData: BrtData[] = [];
```

footer.component.html
```
<bruit-io id="bruit" [config]="bruitConfig" [data]="bruitData">
```

J'ai une erreur de compilation : 

`
ERROR in node_modules/@bruit/component/dist/types/stencil.core.d.ts(133,23): error TS2315: Type 'CustomEvent' is not generic.
node_modules/@bruit/component/dist/types/stencil.core.d.ts(202,46): error TS2304: Cannot find name 'HTMLDialogElement'.
`

En supprimant le type, ça passe :
footer.component.ts
```
public readonly bruitData = [];
```

**Comment by lamstutz** [comment]
typescript < 2.7
