### ISSUE TITLE
Copying and pasting buggy on app website

### ISSUE THREAD

**Issue by wrabit** [Moventes/bruit.io#23]
Copying and pasting does not work on the website. A dialog appears that states 'Copied to clipboard' but it's not.

Latest MacOS
Latest Stable Chrome

Using cmd + c & cmd +v OR right click, copy

**Comment by ghost** [comment]
Hi,
Thank you for your feedback, we will be looking into it.

**Comment by ghost** [comment]
This has been corrected, will be made available soon
