### ISSUE TITLE
Problème d'encodage sous Safari

### ISSUE THREAD

**Issue by pedubreuil** [Moventes/bruit.io#32]
Erreur de décodage côté serveur en cas d'appel depuis Safari: LZString.decompressFromUTF16()

**Comment by gwNO-syd** [comment]
Une idée à creuser : il semble que le probleme puisse etre du au boundary (header 'content-type'="multipart/formdata;boundary=xxxxxxxx"). Ce header n'est pas préset avec la requete car si on le place à la main le boundary ne correspond pas à celui fourni par le navigateur => requete non traité.
Il a existé un probleme avec safari qui générait le content type comme étant du xml ce qui rentre en contradiction avec le contenu form-data...
Je ne suis pas sur de ce que j'avance mais cela peut etre la cause
