### ISSUE TITLE
How to open the Feedback window with javascript?

### ISSUE THREAD

**Issue by sowinski** [Moventes/bruit.io#33]
Hi,

I created a "FEEDBACK" Button on my website and would like to open the Feedback window on a click event.

How can I open the Feedback window with JavaScript?

Thx

**Comment by gwNO-syd** [comment]
Hi,
For now, the window opening is not based on a click event but uses a custom dom element : <bruit-io></bruit-io>
You can insert your button in it like in the following example:

```html
<bruit-io id="bruit"><button>FOO</button></bruit-io>
<script>
  var bruit = document.getElementById('bruit');
  var config = {
    form: [{
      label: 'bar',
      type: 'checkbox'
    }, {
      label: 'baz',
      id:'agreement',
      type: 'checkbox'
    }],
    apiKey: 'xxxxxxxxxxxx'
  };
  bruit.setAttribute('config', JSON.stringify(config));
</script>
```

Of course, you need to use your own config...
