### ISSUE TITLE
CORS issue with images in screenshot

### ISSUE THREAD

**Issue by chrisj74** [Moventes/bruit.io#49]
Hi, just getting started with Bruit and so far loving it. However, I do have one request I think would improve it even more.
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
I see you are using html2canvas for screenshots, but cannot see a way to pass through options. Specifically, I need to se the `useCORS: true` option. At the moment my screenshots do not render any images as they are coming from another domain.

**Expected behavior:**
It would be great to either expose all the html2canvas options or at least allow the `useCORS` option to be set to true. Failing this any guidance on how to update this in a fork would be great.

**Steps to reproduce:**
N/A

**Related code:**
N/A
```
insert any relevant code here
```

**Other information:**
I am using this with a Vue js app built with the Quasar framework.

**Comment by lamstutz** [comment]
Thanks @chrisj74 ,
This issue is solved in v1.3.3.
(Warning! the documentation has changed for component initialization)
