### ISSUE TITLE
When the agreement checkbox is present, it should be required

### ISSUE THREAD

**Issue by jonrkarr** [Moventes/bruit.io#63]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Currently, when the "agreement" is set to `required: true` and the agreement checkbox is not checked, the modal window does not display an error when users click the "send" button.

Bruit configuration
```
bruitConfig: {
  form: [
    {
      id: 'agreement',
      type: 'checkbox',
      label:
        'I also agree to send a screenshot and technical information about my browser',
      value: false,
      required: true,
    },
  ],
}
```

JavaScript error
```
An invalid form control with name='agreement' is not focusable.
```

**Expected behavior:**
- The agreement checkbox should be marked with `*` when `required: true`
- When the agreement checkbox is required, the checkbox is unchecked, and a user clicks the "send" button, Bruit should display an error message which indicates that the checkbox must be checked.
  - Alternatively, the "send" button should be disabled when the form is invalid.

**Comment by lamstutz** [comment]
@jonrkarr its fix in **1.3.13**

thanks for your feedback
