### ISSUE TITLE
Bug bruit sur clepsydre

### ISSUE THREAD

**Issue by Chaves-Pereira** [Moventes/bruit.io#64]
![image](https://user-images.githubusercontent.com/20415522/72908773-439b4900-3d36-11ea-996a-983c74be76aa.png)

**Comment by lamstutz** [comment]
console.error par angular, sur firefox lié à l’événement click. ca se produit saulement dans la configuration firefox=>ionic=>angular=>bruit.
n’empêche pas le fonctionnement de bruit
