### ISSUE TITLE
Bruit website and service are down

### ISSUE THREAD

**Issue by jonrkarr** [Moventes/bruit.io#66]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
The bruit website and service are down. https://bruit.io/ returns a 503 error.

**Comment by pedubreuil** [comment]
We are truly sorry: our monitoring tools failed to alert us about this.
Bug fixed, and improvments are in progress to avoid this to happen again
